version: "3"

services:
  myazo:
    container_name: myazo
    restart: always
    build: .
    ports:
      - 7020:80
    volumes:
      - myazo-data:/app/data

volumes:
  myazo-data:
    driver: local
